# Generated by Django 2.2.4 on 2019-10-30 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Имя персонала')),
                ('last_name', models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Фамилия персонала')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер тел.')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рожд-я')),
                ('country', models.CharField(blank=True, default='Россия', max_length=64, null=True, verbose_name='Страна')),
                ('town', models.CharField(blank=True, default='Курск', max_length=64, verbose_name='Город')),
                ('description', models.TextField(blank=True, default=None, max_length=512, null=True, verbose_name='Описание персонала')),
                ('vk', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка VK')),
                ('instagram', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка instagram')),
                ('twitter', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка twitter')),
                ('facebook', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность персонала')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования записи')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='GuideStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Статус', max_length=128, verbose_name='Статус турнира')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Статус турнира',
                'verbose_name_plural': 'Статус турнира',
            },
        ),
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guide_images/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия фото')),
                ('guide', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guide.Guide', verbose_name='Персонал')),
            ],
            options={
                'verbose_name': 'Фотография персонала',
                'verbose_name_plural': 'Фотографии персоналов',
            },
        ),
        migrations.AddField(
            model_name='guide',
            name='status',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='guide.GuideStatus', verbose_name='Статус персонала'),
        ),
    ]
