# Generated by Django 2.2.4 on 2019-10-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidestatus',
            options={'verbose_name': 'Статус персонала', 'verbose_name_plural': 'Статус персонала'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='first_name',
            field=models.CharField(blank=True, default=True, max_length=128, null=True, verbose_name='Имя персонала'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='last_name',
            field=models.CharField(blank=True, default=True, max_length=128, null=True, verbose_name='Фамилия персонала'),
        ),
    ]
