# Generated by Django 2.2.4 on 2019-08-17 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Название трансляции')),
                ('url', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка на ТРАНСЛЯЦИЮ с YOUTUBE')),
                ('is_active', models.BooleanField(default=None, null=None, verbose_name='Актуальность турнира')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Трансляция соревнования',
                'verbose_name_plural': 'Трансляция соревнований',
            },
        ),
    ]
