# Generated by Django 2.2.4 on 2019-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='is_active',
            field=models.BooleanField(default=None, null=True, verbose_name='Актуальность турнира'),
        ),
    ]
