# Generated by Django 2.2.4 on 2019-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_auto_20190817_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='is_active',
            field=models.BooleanField(default=None, verbose_name='Актуальность турнира'),
        ),
    ]
