# Generated by Django 2.2.4 on 2019-08-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_auto_20190817_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast',
            old_name='ssilka',
            new_name='url',
        ),
    ]
