# Generated by Django 2.2.4 on 2019-10-24 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutopsyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Статус', max_length=128, verbose_name='Статус пробы Б ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность статуса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Статус пробы Б',
                'verbose_name_plural': 'Статус пробы Б',
            },
        ),
        migrations.CreateModel(
            name='Doping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Название лаборатории')),
                ('illicit_drugs', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Список тестируемых препаратов')),
                ('anti_doping_rules', models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='Антидопинговые правила')),
                ('is_active', models.BooleanField(default=None, verbose_name='Лаборатория лицензированная?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.CreateModel(
            name='Autopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя спортсмена')),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия спортсмена')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество спортсмена')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер телефона')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность статуса')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('status', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='doping_testing.AutopsyStatus', verbose_name='Статус теста')),
            ],
            options={
                'verbose_name': 'Вскрытие пробы Б (заявки и результат)',
                'verbose_name_plural': 'Вскрытие пробы Б (заявки и результат)',
            },
        ),
    ]
