# Generated by Django 2.2.4 on 2019-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doping_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doping',
            name='anti_doping_rules',
            field=models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Антидопинговые правила'),
        ),
    ]
