# Generated by Django 2.2.4 on 2019-08-27 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20190815_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата редактирования турнира'),
        ),
    ]
