# Generated by Django 2.2.4 on 2019-10-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20190827_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsmanInTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='Турнир')),
            ],
        ),
    ]
