# Generated by Django 2.2.4 on 2019-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(blank=True, default=True, max_length=32, null=True, verbose_name='Имя'),
        ),
    ]
