# Generated by Django 2.2.4 on 2019-11-01 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Статус', max_length=128, verbose_name='Статус представителя ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность статуса')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Статус представителя',
                'verbose_name_plural': 'Статус представителей',
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер телефона')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность статуса')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('status', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='regional_representation.RegionalStatus', verbose_name='Статус представителя')),
            ],
            options={
                'verbose_name': 'Региональный представитель',
                'verbose_name_plural': 'Региональные представители',
            },
        ),
    ]
