# Generated by Django 2.2.4 on 2019-08-27 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0005_auto_20190827_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Возрастная кат-ия')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастные категории',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Дисциплина')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Дивизион')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Пол')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность пола')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Пол спортсмена',
                'verbose_name_plural': 'Пол спортсменов',
            },
        ),
        migrations.CreateModel(
            name='Line_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Команда')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность команды')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Лично/Командно',
                'verbose_name_plural': 'Лично/Командно',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Статус')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность статуса')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Статус спортсмена',
                'verbose_name_plural': 'Статусы спортсменов',
            },
        ),
        migrations.CreateModel(
            name='Weight_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Весовая кат-ия')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуальность')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия турнира')),
            ],
            options={
                'verbose_name': 'Весовая категория',
                'verbose_name_plural': 'Весовые категории',
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер тел.')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рожд-я')),
                ('raised_weight', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, verbose_name='Поднятый вес (общий)')),
                ('wilkes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Коэффициент Уилкса')),
                ('country', models.CharField(blank=True, default='Россия', max_length=64, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Регион')),
                ('town', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Город')),
                ('trainer', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Тренер')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Явка')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата завяления')),
                ('updated', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ред-ия записи')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Age_category', verbose_name='Возраст. кат-ия')),
                ('discipline', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Discipline', verbose_name='Дисциплина')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Division', verbose_name='Дивизион')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Gender', verbose_name='Пол')),
                ('status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Status', verbose_name='Статус')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Line_up', verbose_name='Команда/Лично')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament', verbose_name='Турнир')),
                ('weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Weight_category', verbose_name='Весовая кат-ия')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
    ]
