# Generated by Django 2.2.4 on 2019-09-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_auto_20190922_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Status', verbose_name='Статус'),
        ),
    ]
