# Generated by Django 2.2.4 on 2019-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0003_auto_20190923_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='team_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='wilkes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='КУ'),
        ),
    ]
