# Generated by Django 2.2.4 on 2019-12-19 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0004_auto_20191204_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=True, max_length=512, null=True, verbose_name='Название турнира')),
                ('short_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Сокращенное название турнира')),
                ('country', models.CharField(blank=True, default='Россия', max_length=64, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='Курская область', max_length=64, verbose_name='Регион')),
                ('town', models.CharField(blank=True, default='Курск', max_length=64, verbose_name='Город')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата начала турнира')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания турнира')),
                ('sponsors', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Спонсоры')),
                ('description', models.TextField(blank=True, default=None, max_length=512, null=True, verbose_name='Описание турнира')),
                ('provisions_dk', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Положения на турнир с допинг-контролем')),
                ('provisions_bezdk', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Положения на турнир без допинг-контроля')),
                ('nominations', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Номинации на турнир')),
                ('photo_vk', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка на альбом VK')),
                ('video_youtube', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка на видео YOUTUBE')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность турнира')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания турнира')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования турнира')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Статус', max_length=128, verbose_name='Статус турнира')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата созд-ия записи')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Статус турнира',
                'verbose_name_plural': 'Статус турнира',
            },
        ),
        migrations.CreateModel(
            name='TournamentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tournaments_images/', verbose_name='АФиша')),
                ('is_main', models.BooleanField(default=False, verbose_name='Обложка турнира?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата ред-ия фото')),
                ('tournament', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Фотография турнира',
                'verbose_name_plural': 'Фотографии турниров',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='sportsman.TournamentStatus', verbose_name='Статус турнира'),
        ),
    ]
