# Generated by Django 2.2.4 on 2019-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0005_auto_20191219_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentimage',
            name='image',
            field=models.ImageField(upload_to='tournament_image/', verbose_name='АФиша'),
        ),
    ]
